frr version 8.4_git
frr defaults traditional
hostname SpaceBody-R1
ipv6 forwarding
!
interface eth1
 ipv6 address 2001:DB8:2:0:4::2/126
!
interface eth2
 ipv6 address 2001:DB8:2:0:2::2/126
!
interface eth3
 ipv6 address 2001:DB8:2:2::1/64
 ipv6 nd prefix 2001:db8:2:2::/64
 ipv6 nd ra-interval 5
 no ipv6 nd suppress-ra
!
ipv6 route 2001:DB8:2:1::/64 2001:DB8:2:0:2::1
ipv6 route ::/0 2001:DB8:2:0:4::1
