frr version 8.4_git
frr defaults traditional
hostname GS3
ipv6 forwarding
!
interface eth1
 ipv6 address 2001:DB8::3/112
!
interface eth2
 ipv6 address 2001:DB8:1:0:4::2/126
!
ipv6 route 2001:DB8:2::/48 2001:DB8::1001
ipv6 route ::/0 2001:DB8:1:0:4::1
